(ns git-hooks.install
  (:require [clojure.java.io :as io]
            [clojure.string :refer [trim]]
            [clojure.java.shell :refer [sh]]))

(defn make-executable [hook-file]
  (.setExecutable hook-file true))

(defn git-root-directory []
  (trim (:out (sh "git" "rev-parse" "--show-toplevel"))))

(defn project-directory-path [project-root]
  (when-let [dir (git-root-directory)]
    (let [git (.getCanonicalPath (io/file dir))
          lein (.getCanonicalPath (io/file project-root))
          relative-path (subs lein (count git))]
      (str "." relative-path))))

(def hook-template "#!/bin/bash
# @@lein-git-hooks
# Auto-generated by lein-git-hooks. Do not make manual changes.
#
cd %s
lein git-hooks run %s
")

(defn hook-directory []
  (when-let [dir (git-root-directory)]
    (io/file dir ".git" "hooks")))

(defn hook-file [hook-type]
  (io/file (hook-directory) hook-type))

(defn create-hook! [hook-type project-root]
  (let [file (hook-file hook-type)
        content (format hook-template (project-directory-path project-root) hook-type)]
    (spit file content)
    (make-executable file)))

(defn install! [hook-types project-root]
  (doseq [hook-type hook-types] (create-hook! hook-type project-root)))
